default: &default
  adapter: postgresql

development:
  <<: *default
  database: rails-has-many-belongs-to-collection-select-development

test:
  <<: *default
  database: rails-has-many-belongs-to-collection-select-test
